# Generated by Django 3.2.7 on 2023-02-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20230225_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='PurchaseNone',
        ),
    ]
