# Generated by Django 3.2.7 on 2023-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Тариф оплаты',
                'verbose_name_plural': 'Тарифы оплат',
            },
        ),
    ]
