# Generated by Django 3.2.7 on 2023-02-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrates', '0001_initial'),
        ('auth2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='orders_left',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='payrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrates.payrate', verbose_name='Ставка оклада'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='orders_done',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество выполненнх заказов'),
        ),
    ]
