# Generated by Django 3.2.7 on 2023-02-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='orders_done',
        ),
    ]
