# Generated by Django 3.2.7 on 2023-02-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_remove_freelancerprofile_orders_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_freelancer',
            field=models.BooleanField(default=False, verbose_name='Активный фрилансер'),
        ),
    ]
