# Generated by Django 3.2.7 on 2023-02-23 13:15

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=30, verbose_name='Телеграм чат ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('description', models.TextField(blank='', default='', verbose_name='Описание')),
                ('orders_amount', models.PositiveSmallIntegerField(verbose_name='Количество заказов')),
                ('can_conversate_freelancer', models.BooleanField(default=False, verbose_name='Может общаться с фрилансером')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
            bases=('products.product',),
        ),
    ]
